[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "dmlcloud"
description = "Painless distributed training with torch"
version = "0.4"
authors = [
    { name = "Sebastian Hoffmann", email = "shoffmann@bgc-jena.mpg.de"},
]
maintainers = [
    { name = "Sebastian Hoffmann", email = "shoffmann@bgc-jena.mpg.de"},
]
readme = "README.md"
license-files = ["LICENSE"]

requires-python = ">=3.10"
dependencies = [
    "torch~=2.5",
    "torchmetrics~=1.6",
    "progress_table>=2.2.0",
    "numpy",
    "xarray",
    "nvidia-ml-py",
    "omegaconf~=2.3"
]

[project.urls]
Repository = "https://github.com/sehoffmann/dmlcloud"

[project.scripts]
dmlrun = "dmlcloud.run:main"

[dependency-groups]
dev = [
    "pre-commit",
    "pytest",
    "coverage",
    "sphinx",
    "sphinx-rtd-theme",
    "sphinx-autodoc-typehints",
]

[tool.black]
skip-string-normalization = true
line-length = 120
target-version = ["py310", "py311", "py312", "py313"]

[tool.uv]
python-preference = "managed"
